permissions:
  contents: write

steps:
  - uses: actions/checkout@v3

  - name: Configure Git
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

  - name: Commit and Push
    run: |
      git add --all
      git commit -m "Deploy site" || echo "No changes to commit"
      git push origin gh-pages
